// Font Awesome v5 — central registration
// Import only what you use here to keep bundle lean
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faPlug,
  faFileExcel,
  faRobot,
  faServer,
  faCodeBranch,
  faChartBar,
  faLayerGroup,
  faClock,
  faLink,
  faExclamationTriangle,
  faTable,
  faChartLine,
  faCog,
  faRocket,
  faShieldAlt,
  faChartArea,
  faUsers,
  faEye,
  faHandshake,
  faCheckCircle,
  faCode,
  faMicrochip,
  faDatabase,
  faNetworkWired,
  faCloud,
  faLock,
  faEnvelope,
  faPhone,
  faBrain,
  faStar,
  faWrench,
  faArrowRight,
  faArrowDown,
  faBars,
  faTimes,
  faComments,
  faCalendarAlt,
  faPaperPlane,
  faSync,
  faProjectDiagram,
  faFilter,
  faGlobe,
  faHeadset,
  faQuestionCircle,
  faInfoCircle,
  faThumbsUp,
  faMoneyBillWave,
  faBell,
  faSearch,
  faTerminal,
  faInfinity,
  faSlidersH,
  faShoppingCart,
  faTags,
  faUser,
  faBuilding,
  faChevronRight,
  faChevronDown,
  faPlay,
  faBolt,
  faTools,
  faMapMarkerAlt,
  faUserCircle,
} from "@fortawesome/free-solid-svg-icons";

import {
  faWhatsapp,
  faTelegram,
  faGithub,
  faLinkedin,
  faGoogle,
  faNodeJs,
  faDocker,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  // Solid
  faPlug, faFileExcel, faRobot, faServer, faCodeBranch, faChartBar,
  faLayerGroup, faClock, faLink, faExclamationTriangle, faTable, faChartLine,
  faCog, faRocket, faShieldAlt, faChartArea, faUsers, faEye, faHandshake,
  faCheckCircle, faCode, faMicrochip, faDatabase, faNetworkWired, faCloud,
  faLock, faEnvelope, faPhone, faBrain, faStar, faWrench, faArrowRight,
  faArrowDown, faBars, faTimes, faComments, faCalendarAlt, faPaperPlane,
  faSync, faProjectDiagram, faFilter, faGlobe, faHeadset, faQuestionCircle,
  faInfoCircle, faThumbsUp, faMoneyBillWave, faBell, faSearch, faTerminal,
  faInfinity, faSlidersH, faShoppingCart, faTags, faUser, faBuilding,
  faChevronRight, faChevronDown, faPlay, faBolt, faTools, faMapMarkerAlt,
  faUserCircle,
  // Brands
  faWhatsapp, faTelegram, faGithub, faLinkedin, faGoogle, faNodeJs, faDocker
);
