"use client";
// This module re-exports FA icons for direct use in components
// Import directly to avoid library registration issues in Next.js App Router

export { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// Solid icons
export {
  faPlug,
  faFileExcel,
  faRobot,
  faServer,
  faCodeBranch,
  faChartBar,
  faLayerGroup,
  faClock,
  faLink,
  faExclamationTriangle,
  faTable,
  faChartLine,
  faCog,
  faRocket,
  faShieldAlt,
  faChartArea,
  faUsers,
  faEye,
  faHandshake,
  faCheckCircle,
  faCode,
  faMicrochip,
  faDatabase,
  faNetworkWired,
  faCloud,
  faLock,
  faEnvelope,
  faPhone,
  faBrain,
  faStar,
  faWrench,
  faArrowRight,
  faArrowDown,
  faBars,
  faTimes,
  faComments,
  faCalendarAlt,
  faPaperPlane,
  faSync,
  faProjectDiagram,
  faFilter,
  faGlobe,
  faHeadset,
  faChevronRight,
  faChevronDown,
  faPlay,
  faBolt,
  faTools,
  faMoneyBillWave,
  faBell,
  faTerminal,
  faLayerGroup as faLayerGroupAlt,
  faSlidersH,
  faShoppingCart,
  faTags,
  faUser,
  faBuilding,
} from "@fortawesome/free-solid-svg-icons";

// Brand icons
export {
  faWhatsapp,
  faTelegram,
  faGithub,
  faLinkedin,
  faGoogle,
  faNodeJs,
  faDocker,
} from "@fortawesome/free-brands-svg-icons";
